### ISSUE TITLE
Vue UI

### ISSUE THREAD

**Issue by Berkmann18** [Berkmann18/PredictedResultReview#4]
## Proposal
Building a UI (in VueJS).

## Motivation
It would allow people to have a front-end for this project that would make it easy to use.

## Tasks
- [x] UI with components for current data, old data, forecast and old/current difference
- [x] Line numbers on each relevant components
- [x] Connection with the back-end
- [x] Coloured diff output

**Comment by Berkmann18** [comment]
Since I couldn't see the application (so 360c143 is just a safety commit), I'm leaving the line number task unchecked.
